version: '3'

services:
  app:
    volumes:
      - .:/app
  db:
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    ports:
      - "8088:8080"
    depends_on:
      - db
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
